services:
  db:
    image: postgres
    container_name: postgres_expense_tracker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql
    restart: unless-stopped
  app:
    image: ghcr.io/dilankaher/expense_tracker:latest
    ports:
      - "8086:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
