services:
  db:
    image: postgres
    container_name: postgres_expense_tracker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker
    volumes:
      - ./postgres_data:/var/lib/postgresql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 150M

  app:
    image: ghcr.io/dilankaher/expense_tracker:latest
    ports:
      - "8086:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 350M

volumes:
  postgres_data:
